[package]
name = "bar"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = { version = "0.4.40", default-features = false, features = ["clock"] }
nix = { version = "0.30.1", features = ["time"] }
